FROM nginx:latest

# RUN rm /etc/nginx/nginx.conf /etc/nginx/conf.d/default.conf
# COPY nginx.conf /etc/nginx/nginx.conf

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY resolv.conf /etc/resolv.conf