version: '2.2'

services:
    my-proxy:
        build: ./
        restart: unless-stopped

        # port definitions need to be moved to the 'husarnet' service
        network_mode: service:husarnet
        depends_on:
            - "husarnet"

    husarnet:
        image: husarnet/husarnet
        restart: unless-stopped
        ports:
            - "80:8080" # from my-proxy
        volumes:
            - /var/lib/husarnet  # This will persist your Husarnet Client keys, thus IP of the container will be stable/the same between (re)boots
        sysctls:
            - net.ipv6.conf.all.disable_ipv6=0  # Husarnet is using IPv6 for the internal connections
        cap_add:
            - NET_ADMIN
        devices:
            - /dev/net/tun
        env_file: 
            - ./.env  # create .env file in the same folder as Dockerfile and specify HOSTNAME and JOINCODE there
